name: Open new PR on comment

on:
  issue_comment:
    types: [created]

jobs:
  open_pr:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, 'Open PR')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check status
        run: git status

      - name: Checkout PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr checkout ${{ github.event.issue.number }}
