name: cherry-pick

on:
  issue_comment:
    types: [created]

jobs:
  process_comment:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, 'cherry-pick')
    runs-on: ubuntu-latest
    outputs:
      commits: ${{ steps.command.outputs.commits }}
      branches: ${{ steps.command.outputs.branches }}
      branch_matrix: ${{ steps.command.outputs.branch_matrix }}
    steps:
      - name: Parse cherry-pick command
        # TODO: make this step into a separate job, so that we can handle more than one command per comment
        id: command
        shell: bash
        run: |
          set -f
          command=($(echo "${{ github.event.comment.body }}" | grep -m 1 cherry-pick))
          command=("${command[@]:1}")

          has_separator=false
          arg_type=hash
          commits=()
          branches=()
          for token in ${command[@]}; do
            if [[ "$token" == "into" ]]; then
              arg_type=branch
              has_separator=true
            else
              if [[ "$arg_type" == "hash" ]]; then
                commits+=( $token )
              elif [[ "$arg_type" == "branch" ]]; then
                branches+=( $token )
              fi
            fi
          done
          if [ "$has_separator" = false ]; then
            echo "::error::Syntax error in cherry-pick command: missing separator."
            exit 1
          fi

          # Output lists of commits and branches
          echo "commits=${commits[@]}" >> $GITHUB_OUTPUT
          echo "branches=${branches[@]}" >> $GITHUB_OUTPUT

          # We also output the list of branches as json, so they can be used to generate a matrix for the next job 
          echo "branch_matrix=$(jq -cn '$ARGS.positional' --args -- "${branches[@]}")" >> $GITHUB_OUTPUT
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We need the history of all branches for sanity checks
          fetch-depth: 0

      - name: Sanity checks
        run: |
          # Ideally we want all pull requests opened from a given command to be correct and successfull, so that
          # developers don't have to reissue a cherry-pick command for a subset of the commits/branches.
          # Therefore, we do all possible sanity checks here, before any pull request is opened.

          # Check if PR has been merged
          if [[ "${{ github.event.issue.pull_request.merged_at }}" == "" ]]; then
            echo "::error::Pull request has not been merged yet. Cannot cherry-pick commits."
            exit 1
          fi

          # Check that the commits to cherry-pick are actually part of this PRs target branch
          target=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}" | jq -r .base.ref)
          for commit in ${{ steps.command.outputs.commits }}; do
            if git merge-base --is-ancestor ${commit} origin/$target; then 
              echo "Commit $commit found in $target branch."
            else
              echo "::error::Could not find commit $commit in $target branch."
              exit 1
            fi
          done

          # Check that cherry-pick target branches actually exist
          for branch in ${{ steps.command.outputs.branches }}; do
            if [[ -n "$(git ls-remote --heads origin ${branch})" ]]; then
              echo "Found branch $branch in repository."
            else
              echo "::error::Could not find branch $branch in repository."
              exit 1
            fi
          done

          # Check that branches with the cherry-picked commits have not been pushed to the remote yet
          for branch in ${{ steps.command.outputs.branches }}; do
            new_branch=cherry_pick_from_pr${{ github.event.issue.number }}_into_$branch
            if [[ -z "$(git ls-remote --heads origin $new_branch)" ]]; then
              echo "No previous attempt to cherry-pick commits from this PR into branch $branch found."
            else
              echo "::error::Found branch $new_branch in repository."
              echo "::error::It seems there was a previous attempt to cherry-pick commits from this PR into branch $branch."
              echo "::error::If the current cherry-pick attempt is for a different set of commits, make sure that"
              echo "::error::the previous attempt is fully merged and that the corresponding branch has been deleted."
              exit 1
            fi
          done
  
  create_pr:
    runs-on: ubuntu-latest 
    needs: process_comment
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        branch: ${{ fromJson(needs.process_comment.outputs.branch_matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We need the history of all branches
          fetch-depth: 0
 
      - name: Cherry-pick commits
        id: cherry-pick
        continue-on-error: true
        run: |
          #git config user.name ${{ vars.GH_ACTIONS_BOT_GIT_USER_NAME }}
          #git config user.email ${{ vars.GH_ACTIONS_BOT_GIT_USER_EMAIL }}
          git config user.name "Micael Oliveira"
          git config user.email micael.oliveira@anu.edu.au
        
          new_branch=cherry_pick_from_pr${{ github.event.issue.number }}_into_${{ matrix.branch }}
          echo "new_branch=$new_branch" >> $GITHUB_OUTPUT

          git checkout -b $new_branch origin/${{ matrix.branch }}
          git cherry-pick ${{ needs.process_comment.outputs.commits }}

      - name: Open pull request
        if: steps.cherry-pick.outcome == 'success'
        id: open_pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git push --set-upstream origin ${{ steps.cherry-pick.outputs.new_branch }}
          url=$(gh pr create -B ${{ matrix.branch }} -t "Cherry-pick commits from #${{ github.event.issue.number }}" \
            -b "Cherry-picking commits ${{ needs.process_comment.outputs.commits }} from #${{ github.event.issue.number }} into ${{ matrix.branch }}.")
          echo "pr_url=$url" >> $GITHUB_OUTPUT

      - name: Manual cherry-pick instructions
        if: steps.cherry-pick.outcome == 'failure'
        shell: bash
        run: |
          read -r -d '' body <<- EOM
            Automatic Git cherry-picking of commits ${{ needs.process_comment.outputs.commits }} into branch ${{ matrix.branch }} failed.
            This usually happens when cherry-picking results in a conflic or an empty commit.
            To manually cherry-pick the commits and open a pull request, please follow these instructions:
            1. Create new branch from target branch:
            console
            git checkout origin/${{ matrix.branch }}
            git pull
            git checkout -b ${{ steps.cherry-pick.outputs.new_branch }}
            
            2. Cherry-pick commits:
            console
            git cherry-pick ${{ needs.process_comment.outputs.commits }}
            
            3. Fix any conflicts and/or empty commits by following the instructions provided by Git.
            4. Push the new branch:
            console
            git push --set-upstream origin ${{ steps.cherry-pick.outputs.new_branch }}
            
            5. Open a new pull request on github making sure the target branch is set to ${{ matrix.branch }}.
          EOM
          echo "$body"
          gh pr comment ${{ github.event.issue.number }} --body "$body"
    
#      - name: Checkout PR
        # Since this is triggerd by a comment, the checkout repository step will
        # checkout the main branch, not the one from the PR.
#        env:
#          GH_TOKEN: ${{ github.token }}
#        run: gh pr checkout ${{ github.event.issue.number }}


#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
