name: Open new PR on comment

on:
  issue_comment:
    types: [created]

jobs:
  open_pr:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, 'Open PR')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: cli/gh-actions@v2
        with:
          version: latest

      - name: Create new branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b new-branch

      - name: Push new branch
        run: |
          git push origin new-branch

      - name: Create new pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "New Pull Request" --body "This PR was created automatically" --head new-branch --base main
